version: "3.8"
services:
  tutuplapak-purchase-service:
    build: 
      context: .
      args:
        - APP_PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - MODE=${MODE}
      - PROD_HOST=${PROD_HOST}
      - DEBUG_HOST=${DEBUG_HOST}
      - PORT=${PORT}
      - GPRC_USER_HOST=${GPRC_USER_HOST_DEV}
      - GPRC_USER_PORT=${GPRC_USER_PORT}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
    env_file:
      - .env
    volumes:
      - ./logs:/root/logs
    networks:
      - tutuplapak-network

networks:
  tutuplapak-network:
    external: false    