global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "purchase-service-server"
    static_configs:
      - targets: ["host.docker.internal:8080"] 

  - job_name: "user-service-server"
    static_configs:
      - targets: ["host.docker.internal:8081"] 

  - job_name: "grpc-user-service-server"
    static_configs:
      - targets: ["host.docker.internal:9091"] 