version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
