definitions:
  request.AuthByEmailRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  request.AuthByPhoneRequest:
    properties:
      password:
        maxLength: 32
        minLength: 8
        type: string
      phone:
        type: string
    required:
    - password
    - phone
    type: object
  request.LinkEmailRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  request.LinkPhoneRequest:
    properties:
      phone:
        type: string
    required:
    - phone
    type: object
  request.UpdateUserProfileRequest:
    properties:
      bankAccountHolder:
        maxLength: 32
        minLength: 4
        type: string
      bankAccountName:
        maxLength: 32
        minLength: 4
        type: string
      bankAccountNumber:
        maxLength: 32
        minLength: 4
        type: string
      fileId:
        type: string
    required:
    - bankAccountHolder
    - bankAccountName
    - bankAccountNumber
    type: object
  response.AuthResponse:
    properties:
      email:
        type: string
      phone:
        type: string
      token:
        type: string
    type: object
  response.UserResponse:
    properties:
      bankAccountHolder:
        type: string
      bankAccountName:
        type: string
      bankAccountNumber:
        type: string
      email:
        type: string
      fileId:
        type: string
      fileThumbnailUri:
        type: string
      fileUri:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/login/email:
    post:
      consumes:
      - application/json
      parameters:
      - description: Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.AuthByEmailRequest'
      produces:
      - application/json
      responses:
        "201":
          description: success response
          schema:
            $ref: '#/definitions/response.AuthResponse'
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      tags:
      - Auth
  /v1/login/phone:
    post:
      consumes:
      - application/json
      parameters:
      - description: Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.AuthByPhoneRequest'
      produces:
      - application/json
      responses:
        "201":
          description: success response
          schema:
            $ref: '#/definitions/response.AuthResponse'
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      tags:
      - Auth
  /v1/register/email:
    post:
      consumes:
      - application/json
      parameters:
      - description: Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.AuthByEmailRequest'
      produces:
      - application/json
      responses:
        "201":
          description: success response
          schema:
            $ref: '#/definitions/response.AuthResponse'
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      tags:
      - Auth
  /v1/register/phone:
    post:
      consumes:
      - application/json
      parameters:
      - description: Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.AuthByPhoneRequest'
      produces:
      - application/json
      responses:
        "201":
          description: success response
          schema:
            $ref: '#/definitions/response.AuthResponse'
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      tags:
      - Auth
  /v1/user:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: success response
          schema:
            $ref: '#/definitions/response.UserResponse'
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      tags:
      - UserProfile
    post:
      consumes:
      - application/json
      parameters:
      - description: Update Profile Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUserProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success response
          schema:
            $ref: '#/definitions/response.UserResponse'
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      tags:
      - UserProfile
  /v1/user/link/email:
    post:
      consumes:
      - application/json
      parameters:
      - description: Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LinkEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success response
          schema:
            $ref: '#/definitions/response.UserResponse'
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      tags:
      - UserProfile
  /v1/user/link/phone:
    post:
      consumes:
      - application/json
      parameters:
      - description: Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LinkPhoneRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success response
          schema:
            $ref: '#/definitions/response.UserResponse'
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      tags:
      - UserProfile
swagger: "2.0"
